### ISSUE TITLE
RDS Terminate

### ISSUE THREAD

**Issue by satyajitkoijam** [aws-solutions/operations-conductor#2]
I am trying to terminate the RDS db-instance but Resource Selector found 0 resources as it is not picking RDS with defined tag.
here are few details I provide
- TargetResourceType = rds:dbinstance
- Target Tag = OpsConductorTaskList and added as tag at RDS

Please help, what issue might be and wh

**Comment by ericquinones** [comment]
Hi @satyajitkoijam 

A couple of things to check first:
* Are there any errors being reported in the Resource Selector logs on CloudWatch? If so, can you please let us know what the errors are?
* When creating the task in the Operations Conductor UI, did you include the region with the RDS Instance in the list of regions for this task?

Also, can you please try using `TargetResourceType` = `rds:db` instead of `rds:dbinstance`?

Once the Resource Selector lambda finds your instance(s), the SSM automation document you created should be executed. For more information on the execution, please review the execution details in the AWS Systems Manager console.

Please let us know if you have any other issues.

**Comment by satyajitkoijam** [comment]
thanks @ericquinones 
now it working after changing TargetResourceType = rds:db 
Do you any docs where I can refer for TargetResourceType for other services also

**Comment by ericquinones** [comment]
Hi @satyajitkoijam 

The `TargetResourceType` is in the format of `service:resourceType`, which are taken from the resource's ARN. When the Resource Selector looks for resources that have the `TargetTag` you specified, we also [filter the results](https://github.com/awslabs/operations-conductor/blob/master/source/services/resource-selector/index.ts#L256-L257) to only return resources that match the `TargetResourceType`.

You can look at the ARN of a resource to find out the `service` and `resourceType` that you should combine as `service:resourceType` to set as the value of `TargetTag`. 

[This documentation](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) describes how to find the `service` and `resourceType` from an ARN. Also, [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Tagging.ARN.html) is for RDS specifically where you can see that the `service` should be `rds` and the `resourceType` for an RDS DB instance is `db`.
